### ISSUE TITLE
JobManager::send() must implement interface Smalot\Cups\Model\PrinterInterface

### ISSUE THREAD

**Issue by BrunoFelipeAlbuquerque** [smalot/cups-ipp#9]
After installing and trying to use any of the example code, I'm getting the following error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Smalot\Cups\Manager\JobManager::send() must implement interface Smalot\Cups\Model\PrinterInterface, boolean given, called in /var/www/cups/index.php on line 29 and defined in /var/www/cups/vendor/smalot/cups-ipp/src/Manager/JobManager.php:87 Stack trace: #0 /var/www/cups/index.php(29): Smalot\Cups\Manager\JobManager->send(false, Object(Smalot\Cups\Model\Job)) #1 {main} thrown in /var/www/cups/vendor/smalot/cups-ipp/src/Manager/JobManager.php on line 87`

**Comment by c-scholz-acribit** [comment]
Well it seems like the parameter you assigned when calling `send()` is not an actual `PrinterInterface `but is `false`. I propose you examine the parameter and check if it actually is implementing the `PrinterInterface`.

**Comment by boomsya** [comment]
the same error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Smalot\Cups\Manager\JobManager::getList() must implement interface Smalot\Cups\Model\PrinterInterface, bool given, called in /var/www/html/ipp2/printers_jobs.php on line 19 and defined in /var/www/html/ipp2/vendor/smalot/cups-ipp/src/Manager/JobManager.php:31 

Stack trace: #0 /var/www/html/ipp2/printers_jobs.php(19): 
Smalot\Cups\Manager\JobManager->getList(false, false, 0, 'completed') #1 {main} thrown in /var/www/html/ipp2/vendor/smalot/cups-ipp/src/Manager/JobManager.php on line 31
```

**Comment by HayderHatem** [comment]
the same for me

Argument 1 passed to Smalot\Cups\Manager\JobManager::send() must implement interface Smalot\Cups\Model\PrinterInterface, boolean given, called in /var/www/html/ipp_test/test/app/Http/Controllers/testController.php on line 37

my code 

`` $client = new Client();
        $builder = new Builder();
        $responseParser = new ResponseParser();
       // $client->setAuthorizetion('login', 'password');
        
        $printerManager = new PrinterManager($builder, $client, $responseParser);
        $printer = $printerManager->findByUri('ipp://192.168.10.232:631');
        
        $jobManager = new JobManager($builder, $client, $responseParser);
        
        $job = new Job();
        $job->setName('job create file');
        $job->setUsername('demo');
        $job->setCopies(1);
        $job->setPageRanges('1');
        $job->addFile('./helloworld.pdf');
        $job->addAttribute('media', 'A4');
        $job->addAttribute('fit-to-page', true);
        $result = $jobManager->send($printer, $job); ``

**Comment by HayderHatem** [comment]
the same for me

Argument 1 passed to Smalot\Cups\Manager\JobManager::send() must implement interface Smalot\Cups\Model\PrinterInterface, boolean given, called in /var/www/html/ipp_test/test/app/Http/Controllers/testController.php on line 37

my code

```
$client = new Client();
$builder = new Builder();
$responseParser = new ResponseParser();
// $client->setAuthorizetion('login', 'password');

    $printerManager = new PrinterManager($builder, $client, $responseParser);
    $printer = $printerManager->findByUri('ipp://192.168.10.232:631');
    
    $jobManager = new JobManager($builder, $client, $responseParser);
    
    $job = new Job();
    $job->setName('job create file');
    $job->setUsername('demo');
    $job->setCopies(1);
    $job->setPageRanges('1');
    $job->addFile('./helloworld.pdf');
    $job->addAttribute('media', 'A4');
    $job->addAttribute('fit-to-page', true);
    $result = $jobManager->send($printer, $job);
```

**Comment by c-scholz-acribit** [comment]
You both are aware that the Client class method for authentication in CUPS is called `setAuthentication` and **not** `setAuthorizetion` ? Because you both use this wrong method, `$client` seems not to authenticate and the `$printerManager` probably returns `false` instead of a connected printer. And because of this you probably can't send the job via `$jobManager->send()`.

**Comment by boomsya** [comment]
:) yes, you right
setAuthentication. sorry for my mistakes. Maybe at that time i was works hard and tired
